/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NewRouteImport } from './routes/new'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PapersThreadIdReviewRouteImport } from './routes/papers.$threadId.review'
import { Route as PapersThreadIdProgressRouteImport } from './routes/papers.$threadId.progress'
import { Route as PapersThreadIdDoneRouteImport } from './routes/papers.$threadId.done'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersThreadIdReviewRoute = PapersThreadIdReviewRouteImport.update({
  id: '/papers/$threadId/review',
  path: '/papers/$threadId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersThreadIdProgressRoute = PapersThreadIdProgressRouteImport.update({
  id: '/papers/$threadId/progress',
  path: '/papers/$threadId/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersThreadIdDoneRoute = PapersThreadIdDoneRouteImport.update({
  id: '/papers/$threadId/done',
  path: '/papers/$threadId/done',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/signup': typeof SignupRoute
  '/papers/$threadId/done': typeof PapersThreadIdDoneRoute
  '/papers/$threadId/progress': typeof PapersThreadIdProgressRoute
  '/papers/$threadId/review': typeof PapersThreadIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/signup': typeof SignupRoute
  '/papers/$threadId/done': typeof PapersThreadIdDoneRoute
  '/papers/$threadId/progress': typeof PapersThreadIdProgressRoute
  '/papers/$threadId/review': typeof PapersThreadIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/signup': typeof SignupRoute
  '/papers/$threadId/done': typeof PapersThreadIdDoneRoute
  '/papers/$threadId/progress': typeof PapersThreadIdProgressRoute
  '/papers/$threadId/review': typeof PapersThreadIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/new'
    | '/signup'
    | '/papers/$threadId/done'
    | '/papers/$threadId/progress'
    | '/papers/$threadId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/new'
    | '/signup'
    | '/papers/$threadId/done'
    | '/papers/$threadId/progress'
    | '/papers/$threadId/review'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/new'
    | '/signup'
    | '/papers/$threadId/done'
    | '/papers/$threadId/progress'
    | '/papers/$threadId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  SignupRoute: typeof SignupRoute
  PapersThreadIdDoneRoute: typeof PapersThreadIdDoneRoute
  PapersThreadIdProgressRoute: typeof PapersThreadIdProgressRoute
  PapersThreadIdReviewRoute: typeof PapersThreadIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$threadId/review': {
      id: '/papers/$threadId/review'
      path: '/papers/$threadId/review'
      fullPath: '/papers/$threadId/review'
      preLoaderRoute: typeof PapersThreadIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$threadId/progress': {
      id: '/papers/$threadId/progress'
      path: '/papers/$threadId/progress'
      fullPath: '/papers/$threadId/progress'
      preLoaderRoute: typeof PapersThreadIdProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$threadId/done': {
      id: '/papers/$threadId/done'
      path: '/papers/$threadId/done'
      fullPath: '/papers/$threadId/done'
      preLoaderRoute: typeof PapersThreadIdDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  SignupRoute: SignupRoute,
  PapersThreadIdDoneRoute: PapersThreadIdDoneRoute,
  PapersThreadIdProgressRoute: PapersThreadIdProgressRoute,
  PapersThreadIdReviewRoute: PapersThreadIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
